apiVersion: v1
kind: ConfigMap
metadata:
  name: front-configs
data:
  backend_URL: "http://10.47.6.67"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: footyfreak/objeditfront
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: front-configs

---

apiVersion: v1
kind: Service
metadata:
  name: front-service
  annotations:
    service.msp.ntnx.io/lb: lan_1
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: front-test
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: front-service
          servicePort: 80